import re
F = '/mnt/user-data/outputs/encyklopedie_aion_2.html'
S = open(F, encoding='utf8').read()

def card(t, tag, intro, bl, rew=None, tip=None, col='slate'):
    h = f'<div class="p-5 rounded-xl border border-slate-200 bg-{col}-50/50"><div class="flex items-start justify-between gap-2 mb-2"><h3 class="font-bold text-slate-900 text-base">{t}</h3><span class="text-[10px] font-bold bg-slate-200 text-slate-800 px-2 py-0.5 rounded whitespace-nowrap">{tag}</span></div><p class="text-xs text-slate-700 leading-relaxed mb-2">{intro}</p>'
    h += '<ul class="list-disc pl-4 space-y-1 text-xs text-slate-700 mb-3">' + ''.join(f'<li>{b}</li>' for b in bl) + '</ul>'
    if rew: h += f'<p class="text-xs font-semibold text-slate-800 bg-slate-200/70 p-2 rounded mb-2">🎁 Odměny: {rew}</p>'
    if tip: h += f'<p class="text-xs text-emerald-900 bg-emerald-50 border border-emerald-200 p-2 rounded">💡 Tip: {tip}</p>'
    return h + '</div>'

def sec(i, title, lead, cards):
    return f'<section id="section-{i}" class="tab-content hidden space-y-6"><div class="bg-white rounded-xl p-6 border border-slate-200 shadow-sm"><h2 class="text-2xl font-bold text-slate-900 mb-2">{title}</h2><p class="text-slate-600 text-sm leading-relaxed mb-6">{lead}</p><div class="grid grid-cols-1 lg:grid-cols-2 gap-6">{"".join(cards)}</div></div></section>\n\n    '

def put(i, html):
    global S
    a = S.find(f'<section id="section-{i}"'); b = S.find('<section ', a + 10)
    S = S[:a] + html + S[b:]

ODYLE = sec('odyle', '🧪 Odyle systém', '<strong>Odyle Energy</strong> je zdroj každé postavy, který se odemyká na Lv 22 (quest do Crow Cave). Spotřebovává se při nárokování reward cube po zabití final bosse dungeonu. Bez Odyle Energy dungeon projdeš, ale odměnu z cube nevyzvedneš. Od Odyle Energy je nutné odlišit <strong>Odyle jako surovinu</strong>: gathering node typu Odyle, který se těží přes Essence Extraction.', [
 card('⚡ Co je Odyle Energy', 'Lv 22', 'Resource, který určuje, kolik dungeon odměn za den a týden skutečně vyzvedneš. Každá postava má vlastní pool, který se regeneruje i offline.', [
  'Odemyká se na <strong>Lv 22</strong> během questu v Crow Cave.', 'Utrácí se u Conquest a Transcendence dungeonů, a také u Exploration dungeonů.', 'Alty mají vlastní pool a vlastní regeneraci, proto se vyplatí je co nejdřív dotáhnout na Lv 22.', 'Odyle Energy item přidá dalších 40 energie, Small Odyle Energy 10. Energie z itemů má zvláštní limit 2 000.'], tip='Dotáhni všechny plánované postavy na Lv 22 hned první den, aby jim začala běžet regenerace.', col='emerald'),
 card('⏱️ Regenerace a cap', 'Pasivně', 'Odyle Energy se obnovuje v pevném 3hodinovém cyklu a nad cap se dál nenabírá.', [
  '<strong>+15 každé 3 hodiny</strong>, tedy 120 denně (3 cube po 40).', 'Cap: <strong>560</strong>, s předplatným <strong>840</strong>.', 'Bez předplatného pool přeteče za 4 dny a 16 hodin, s předplatným za 7 dní.', 'Devět hodin offline na capu zahodí 45 energie, což je víc než celý cube.'], tip='Před spaním utrať energii nad cca 500. Přesné hodnoty spočítá Kalkulačka Odyle Energy.'),
 card('🧊 Kolik stojí cube', 'Spotřeba', 'Cena závisí na typu dungeonu a na předplatném.', [
  '<strong>40 Odyle Energy</strong>: Conquest a Transcendence (např. Draupnir, Ferocious Horn Den).', '<strong>20 Odyle Energy</strong>: Exploration cube v Krao Cave a Urugugu Canyon, tedy levný zdroj Enhance Stones pro alty.', '<strong>80 Odyle Energy</strong>: nárokování obou odměn najednou (pouze s předplatným).', '„Remaining Unobtained Cube Count“: 10 týdně na server. Klesá i tehdy, když dungeon opustíš bez cube. Na 0 nelze vstoupit do Conquest ani Transcendence až do středy.'], tip='Když ti dojde energie, přestaň dungeony běhat. Běh bez nárokování cube stojí jeden z 10 týdenních slotů.', col='amber'),
 card('🛒 Jak získat Odyle Energy', 'Všechny zdroje', 'Odyle Energy se získává výhradně z těchto zdrojů:', [
  '<strong>Pasivní regenerace</strong>: 15 / 3 h (zdarma, vždy).', '<strong>Substance Morph (Craft)</strong>: týdně 20 Odyle craftů na main, plus 4 na každého altu.', '<strong>Subscriber Shop (Wind Breeze Merchant)</strong>: týdně 20 Odyle na main, plus 4 na každého altu. Vyžaduje předplatné.', '<strong>Odyle Energy a Small Odyle Energy itemy</strong>: přidávají 40 / 10 energie po použití.', 'Hlavní odměnou Duty Missions a Command questů je Kinah a Abyss Points. Odyle Energy item se mezi jejich zaručenými odměnami neuvádí.'], tip='Odyle craft a nákup v Subscriber Shopu měj v týdenní rutině, limity se každou středu vrací.', col='indigo'),
 card('💎 Odyle jako surovina', 'Essence Extraction', 'Odyle je také jedna ze šesti kategorií gatheringu (Ore, Gem, Log, Herb, Ingredient, Odyle).', [
  'Čtyři kvality: Odyle, Fine Odyle, Pure Odyle, Radiant Odyle. Při těžbě můžeš začít těžit vyšší kvalitu.', 'Skilly Seeker (zobrazí Odyle na minimapě), Plentiful Harvest (až 30 % dvojnásobný výnos) a Appraiser (až 30 % reroll kvality).', 'Node může navíc dát bonus item Poko’s Skin Bundle (Bound).'], tip='Specialty skilly Odyle stojí 7 Specialty Points; celkem jich získáš 14.', col='sky'),
 card('📅 Plán na týden', 'Strategie', 'Takto rozložit Odyle Energy mezi dny:', [
  'Denně: 3 cube po 40 se vejdou do pasivního příjmu.', 'Conquest reward count bankuje 7 dní (21 při +1 / 8 h), Transcendence 7 dní (14 při +1 / 12 h), proto je spotřeba energie limitujícím faktorem.', 'Předplatitelé mají cap 840, takže mohou po celý týden vynechat přihlášení bez ztráty.', 'Pokud hraješ alty, využij jejich vlastní pooly: nejlepší poměr cena/odměna mají cube za 20.'], tip='Odyle Energy je jediný denní čítač, který přetéká dřív než za týden.')])

PVE = sec('pve', '⚔️ PvE kontent', 'Přehled všech hlavních PvE aktivit včetně limitů a odměn. Čísla vycházejí z dat globálního klienta.', [
 card('🏰 Expedice (Exploration & Conquest)', 'Core PvE', 'Dungeony, jejichž odměny se nárokují z reward cube po zabití final bosse. Dělí se na režim Exploration a těžší režim Conquest.', [
  '<strong>Exploration</strong>: 7 reward counts týdně na každý Expedition dungeon, reset ve středu. Cube v Krao Cave a Urugugu Canyon stojí 20 Odyle Energy.', '<strong>Conquest</strong>: reward count +1 / 8 h (cap 21), 35 final-boss kills týdně, cube stojí 40 Odyle Energy.', 'Challenge Ticket přidá jeden reward count.', 'Nárokování cube je podmíněno „Remaining Unobtained Cube Count“ (10 týdně na server).'], 'Enhance Stones, gear, bound Kinah, crafting materiály, Pantheon art (Conquest reward tables).', 'Exploration alty vyčistíš levně za 20 energie, Conquest nech na hlavní postavu.', 'amber'),
 card('📅 Daily Dungeon (Unknown Fissure)', 'Týdenní limit', 'Navzdory názvu se spravuje týdně. Jde o časovku, ve které zabíjíš nepřátele a odměna závisí na výsledném skóre.', [
  '<strong>14 vstupů týdně</strong>, sdílených na celý server (alty další vstupy nedostanou). Reset ve středu.', 'Run trvá 1 minutu 30 sekund, dungeon: Daeva Bio-Research Base.', 'Vstup spotřebuje Unknown Fissure Challenge Ticket, který lze doplnit jedním itemem.', 'Instant Clear Ticket: Daily Dungeon znovu vyzvedne již získanou odměnu (spotřebuje vstup).'], 'odměna podle skóre.', 'Vstupy si šetři na pozdější část týdne, kdy má postava víc síly. Stabilní tempo jsou 2 vstupy denně.'),
 card('🌙 Nightmare', 'Denní pokusy', 'Sólo žebřík bossů, který se odemyká na Lv 45.', [
  '26 bossů po 10 tierech, doporučený power 1 000–4 950.', '<strong>2 pokusy denně</strong>, bank až 14, tracking per postava.', 'Pokus se spotřebuje až za clear, wipe je zdarma.', 'Instant Clear Ticket: Nightmare opakuje clear odměnu (z lobby neuděluje Rank Points). Nightmare Dungeon Challenge Ticket přidá pokus.'], 'Phantasmal Fragments pro Nightmare Shop: první clear 500 (Gatekeeper Pinopi, tier 1) až 3 950, opakovaný clear 100–1 010.', 'Oba denní pokusy vždy použij na nejnižší tier, který jsi ještě nevyčistil.', 'indigo'),
 card('🎪 Shugo Festival', 'Každou hodinu', 'Hodinová minihra pro 4–9 hráčů, která se odemyká na Lv 13.', [
  'Začíná každou celou hodinu (:00), trvá 10 minut a vybírá se jedna náhodná hra (Jump Jump, Nyerk Shooter, Hidden Lugi, Goldrin’s Treasure…).', 'Odměna se nárokuje za Shugo Festival Reward Key: <strong>3 denně</strong>, cap 12 (21 s předplatným), sdíleno na server.', 'Klíč přidává i item Shugo Festival Reward Key.'], 'gear, Abyss Points, Wisdom Stones, Daevanion Crystals.', 'Nenech klíče sedět na capu: po 4 dnech bez hraní se další regenerace zahazuje.', 'sky'),
 card('📦 Supply Request', 'Denní / týdenní', 'Zakázky na odevzdání vybraného gearu, gathering materiálů a dalších surovin.', [
  'Dělí se na denní Emergency Requests, týdenní a sezónní zakázky.', 'Všichni hráči mají stejné požadavky, takže požadované materiály před resetem zdražují.', 'Odměnou jsou Abyss Points a další položky.'], 'Abyss Points a doplňkové odměny.', 'Odevzdávej jen to, co se vyplatí. Někdy je lepší materiál prodat za Kinah.'),
 card('🐉 Sanctuary (Raidy)', 'Týdenní raidy', 'Vrcholný skupinový obsah s limitem pokusů na raid.', [
  '<strong>4 pokusy týdně na každý raid</strong>, spotřebují se při vstupu.', 'Abyssal Forge: Ludra povoluje 1 final-boss kill týdně, Corroded Decontamination Facility a Chalice of Muspel po 2.', 'Abyssal Forge Challenge Ticket přidá pokus, Abyssal Forge Reward Voucher přidá Ludra reward count.'], 'raid odměny za final-boss kill.', 'Raid night si naplánuj hned po resetu. Čtyři pokusy rychle zmizí, když se skupina učí mechaniky.', 'amber'),
 card('✨ Transcendence', 'Item level 1 600', 'Dungeony zaměřené na Arcana: jediný zdroj Arcana karet a Training Arcana.', [
  'Dungeony: <strong>Deus Research Base</strong> (karty Chalice, Compass, Bell) a <strong>Shattered Arkanis</strong> (Chalice, Parchment, Mirror).', 'Reward count +1 / 12 h (cap 14), 28 final-boss kills týdně, cube stojí 40 Odyle Energy.', 'Vyšší tiery (3 a 4) dávají Unique karty.'], 'Arcana karty, Training Arcana.', 'Vyplatí se i s dobrým gearem, protože Arcana zvyšují úroveň skillů.', 'indigo'),
 card('📜 Duty Quests', 'Denně', 'Duty Missions jsou Wanted bounties odemčené na Lv 45.', [
  'Existuje 206 Wanted úkolů, držet lze až 20, odevzdat <strong>5 denně</strong> (limit na server).', 'Každý dá 50 000 bound Kinah a 1 000 Abyss Points.', 'Navíc dostaneš zaručenou odměnu a výběr z náhodných (Crystals, Hidden Cube Keys, Unique nebo gold materiály).'], 'Kinah, Abyss Points, Crystals, Hidden Cube Keys.', 'Splň všech 5 jako první věc po přihlášení. Zabírá to jen pár minut.'),
 card('📑 Command Quests', 'Týdenní nákup', 'Duty Commands jsou svitkové úkoly: 577 různých, držet jich lze 20.', [
  'Redraw lze použít až 10× za Kinah, cena roste z 1 000 na 300 000.', 'Většina dává 1 000 nebo 2 000 Abyss Points, některé i Abyssal Power Shards.', 'Týdenní svitky kupuješ u Command Merchantů: až <strong>12 PvE</strong> na server (hlavní město) a <strong>20 PvP</strong> na server (Abyss merchant).', 'Svitky lze koupit předem a splnit později.'], 'Abyss Points, Abyssal Power Shards.', 'Nákup udělej před týdenním resetem, limity se pak vracejí.', 'emerald'),
 card('🧭 Sealed Dungeons & Hidden Cubes', 'Bez limitu', 'Obsah bez čítače vstupů, vhodný jako výplň při regeneraci limitů.', [
  '161 sólo Sealed Dungeons, každý s clear odměnou včetně 15 000 bound Kinah.', '206 Hidden Cubes na mapách, každý se objevuje na jednom z několika možných míst (celkem 3 722).', 'Gathering node nemá žádný denní limit.'], 'bound Kinah, cube odměny, materiály.', 'Sledování nalezených Hidden Cubes ti usnadní integrovaná mapa.', 'sky')])

PVP = sec('pvp', '🛡️ PvP kontent', 'PvP v Aion 2 se točí kolem Abyssu, ale existují i vyvážené módy. Všechny časy najdeš v liště nahoře.', [
 card('🌌 Abyss Region', 'Lv 45 / item level 1 000', 'Trvalá frakční PvPvE zóna Reshanta, kde se Elyos a Asmodiani střetávají o cíle, bossy a Abyss Points.', [
  'Vstup do Lower Reshanta: <strong>Lv 45 a minimálně 1 000 item level</strong>.', 'Časový limit: <strong>7 hodin týdně na vrstvu</strong> (14 hodin s předplatným u Lower a Middle), počítá se jen uvnitř. Lower/Middle Abyss Rift Stone přidá 1 hodinu, menší kámen 30 minut.', 'Gear v Abyssu <strong>není normalizovaný</strong>, rozdíly v progresi rozhodují o soubojích.', 'Boj probíhá i ve vzduchu: lety, vertikální pozice a útoky shora.', 'Při smrti neztrácíš Abyss Points, ztrácíš pouze ranking points.'], 'Abyss Points, Medals, loot z bossů.', 'Před vstupem si naplánuj úkoly, 7 hodin týdně uteče rychle.', 'rose'),
 card('🏅 Abyss Points & Abyss shop', 'Měna', 'Abyss Points (AP) jsou hlavní progresní měna Abyssu.', [
  'Zdroje: zabití hráčů, Abyss Command Scrolls a Directives, Season Weekly Missions, field a Abyss bossové, Artifact Siege, Abyss Corridors.', 'AP mají <strong>týdenní gain limit</strong>, zvlášť pro PvE a PvP. Po dosažení limitu dostaneš už jen malé množství z Spacetime Rifts. Limit se po resetu zvyšuje.', 'V Abyss shopu kupuješ gear (např. Archon Decanus Longsword za cca 126 000 AP), loot box a wings.', 'AP se podílejí také na progresi Stigma skillů.'], 'gear, wings, Stigma progrese.', 'Kombinuj úkoly: můžeš mít až 5 questů najednou. Vybírej Epic nebo Rare, Common téměř nic nedává.', 'amber'),
 card('🌀 Spacetime Rift', 'Od Lv 45', 'Časově omezený mezifrakční PvP prostor, který se otevírá každé 3 hodiny.', [
  'Portál zůstává otevřený prvních 10 minut, samotný event trvá hodinu.', 'Elyos vstupují do Altgardu, Asmodiani do Verteronu, kde na ně čekají stráže i nepřátelé.', 'Rift obsahuje speciální questy a Sealed Dungeons.', 'Spacetime Rift Ticket přidá 30 minut času v riftu.'], 'Abyss Points; po dosažení týdenního limitu stále malé množství AP.', 'Pokud tě v enemy území zabijí, nelze se oživit kamenem a skončíš doma.', 'indigo'),
 card('⚔️ Battlefield', 'Vyvážený PvP', 'Balanced PvP mód: gear je vyrovnaný, takže rozhodují schopnosti a týmová hra.', [
  '<strong>3 victory rewards týdně na každou postavu</strong>, alty mají vlastní sadu.', 'Na rozdíl od Ascension Trial a Daily Dungeonu nemá smysl výhry šetřit, hraj je, kdy ti to vyhovuje.'], 'victory rewards (3 týdně na postavu).', 'Před vstupem přepni na PvP preset.', 'slate'),
 card('🥊 Arény (1vs1 / 5vs5)', 'Normalizované', 'Malé PvP souboje v normalizovaných módech.', [
  'V malých soubojích je meta jiná než v Abyssu: rozhoduje single-target burst, zatímco v Abyssu se cení AoE, mobilita, healing a CC.', 'Assassin je silný na izolované cíle, ale v Abyssu je méně univerzální.', 'Presets umožňují rychle přepnout gear, Arcana, skilly, title a wings.'], None, 'Vytvoř si samostatný PvP preset a přepni ho před vstupem do Abyssu i arén.', 'rose'),
 card('🏰 Artifact Siege (Abyss Fortress)', 'Po / Čt / So', 'Velká frakční bitva o 3 artefakty v Lower a Middle Abyss. Trvá 30 minut.', [
  'Každý vyhraný artefakt odemkne frakci jeden Abyss Corridor do dalšího sieage.', 'Dimensional Core dostává po 8 minutách debuff Decline of Power (patch z 30. září).', 'Role: tanky chrání healery, DPS brání v přístupu nepřátelům, rozhoduje i kontrola vzdušného prostoru.', 'Nehoň uprchlíky: za úspěšnou obranu nebo dobytí artefaktu dostaneš víc.'], 'Abyss Points, přístup k Corridoru pro frakci.', 'Hraj v partě nebo legionu, sólo hra v siege je velmi obtížná.', 'amber'),
 card('🚪 Abyss Corridors', 'Po siege', 'Krátké časované instance, odemčené podle vyhraných artefaktů.', [
  'Každý Corridor trvá 2 minuty: zabij co nejvíc nepřátel.', 'Procházet je může každá postava, takže alty dávají extra hodnotu.', 'Počet dostupných Corridorů závisí na počtu artefaktů, které tvá frakce drží.'], 'Kinah, Abyss Points.', 'Projdi všechny dostupné Corridory před dalším siege.', 'emerald'),
 card('🐉 World bossové (Abyss)', 'Pevný týdenní rozvrh', 'Abyss má jediný pevný týdenní rozvrh spawnů, uvedený v klientu.', [
  'Lower: <strong>Guardian Lord Nahma</strong> (Pá a Ne, 21:00), <strong>Executor Tamasa / Kaira / Argo</strong> (Po, Čt, So, 21:30), <strong>Watcher Kaira</strong> (každé 3 hodiny).', 'Middle: <strong>Enraged Guardian Lord Nahma</strong> (Pá a Ne), <strong>Turncoat Ducal / Ravager Marakha / Executioner Dramos</strong> (Po, Čt, So).', 'Obě frakce chtějí odměny, takže boj o bosse se rychle změní ve frakční střet.', 'Chyba, které se vyvaruj: nehraj jen DPS na bosse, když tě nepřátelská frakce obchází.'], 'extra loot z bossů, Abyss Points.', 'Hodinu spawnu ověř in-game timerem, den v týdnu je spolehlivý.', 'rose'),
 card('📜 Command Quests v Abyssu', 'Directives', 'Abyss Battle Directives a PvP weekly svitky se plní přímo v Abyssu.', [
  'U Abyss merchanta koupíš až 20 PvP týdenních svitků na server.', 'Až 5 questů najednou, kombinuj cíle, které leží blízko sebe.', 'Rare a Epic questy mají výrazně lepší odměny než Common.'], 'Abyss Points, Abyssal Power Shards.', 'Nákup udělej předem, splnit lze i později.', 'indigo')])

OTHER = sec('other', '🛠️ Ostatní kontent', 'Systémy, které rozvíjejí postavu mimo dungeony a PvP: crafting, vylepšování, kolekce a stat zdroje.', [
 card('🔮 Substance Morph', 'Craft', 'Systém konverze materiálů s recepty a šancemi na úspěch. Obsluhuje ho Morph Merchant (Substance Morph Shop) ve Verteronu a Altgardu.', [
  'Týdně lze vyrobit <strong>20 Odyle Energy</strong> na main a dalších 4 na každého altu.', 'Recepty a vstupní materiály ověř u Morph Merchanta.'], 'Odyle Energy a konvertované materiály.', 'Zahrň ho do týdenní rutiny před resetem.', 'indigo'),
 card('⚒️ Crafting', 'Profese', 'Pět profesí: Blacksmithing, Armorsmithing, Handicrafting, Alchemy a Cooking. Každá se levelí zvlášť.', [
  'Level 1–100: Novice (1–50) a Professional (51–100), na Lv 50 je potřeba promotion quest.', 'Craft běží na Success a Failure Gauge. Neúspěšný craft spotřebuje materiály, ale dá proficiency EXP.', 'Zásah během craftu proces zruší a počítá se jako neúspěch.', 'Craftit lze jen u crafting stations: Elyos v Dawn Legion Base a Zumion Village (Verteron), Asmodiani v Safe Haven a Nornir Assembly (Altgard).', 'Šanci před craftem zobrazí okno Crafting Chance (záložka Expected Probability).'], 'výbava, potiony, jídlo, enhancement materiály.', 'Crafting je nejužitečnější pro materiály k vylepšování gearu.', 'amber'),
 card('✨ Crafting Combo & Splendent', 'Kvalita', 'Combo se může spustit až po úspěšném craftu a vytvoří vylepšenou variantu.', [
  'Combo má vlastní pravděpodobnost, kterou lze přepnout v Expected Probability.', 'Splendent není samostatný grade, ale vylepšený výsledek z Combo, často vyššího gradu.', 'Pozdější recepty Splendent verze vyžadují jako ingredienci.', 'Gradu: Common, Rare, Epic, Unique. Orichalcum zbraně: Common, Splendent Rare, Expert Rare, Expert’s Splendent Epic, Artisan Epic, Artisan’s Splendent Unique, Dragon Lord Unique.'], None, None, 'amber'),
 card('⛏️ Gathering (Essence Extraction)', 'Až Lv 100', 'Gathering se v Aion 2 jmenuje Essence Extraction a nemá samostatné profese.', [
  'Šest kategorií: Ore, Gem, Log, Herb, Ingredient, Odyle.', 'Úroveň 1–100, každý level dává 1 Common Skill Point.', 'Common skilly (max Lv 10): Proficient Handling, Delicate Touch, Lady Luck. Maximum jednoho skillu stojí 40 bodů.', 'Specialty: Seeker, Plentiful Harvest, Appraiser pro každý materiál; celkem získáš 14 bodů (7 na plný strom jednoho materiálu).', 'Reset skillů stojí 50 000 Kinah.'], 'suroviny pro Crafting a Substance Morph.', 'Specialty body rozděl na dvě kategorie, které opravdu potřebuješ.', 'sky'),
 card('🔨 Enhancement', 'Kinah + Enhance Stones', 'Každý kus gearu lze vylepšovat Kinah a Enhance Stones. Šance závisí na gradu, item level ovlivňuje jen cenu.', [
  'Common a Rare: do +5 vždy úspěch. Epic: do +10. <strong>Unique: do +10 bezpečně, max +15</strong>.', 'Unique +10 → +15: 65 % → 50 % → 35 % → 25 % → 20 %, každý neúspěch přidá +5 % k dalšímu pokusu.', 'Neúspěšný pokus stojí jen materiály (výjimkou je PvE rune, která spadne o level).', 'Amplified Enhancement: item level 54 (+1), 70 (+3), 86 (+5), šance 66 % a méně, první krok 600 000 Kinah + 6 Amplify Stone.', 'Potential: 4 kroky na slot za 10 Potential Stone: Abyss a 400 000 Abyss Points, vždy uspěje a dá +2 % PvP Damage Boost nebo Tolerance.'], 'vyšší item level a PvP bonusy.', 'Kolik to bude stát, spočítá Kalkulačka enhancementu.', 'amber'),
 card('🔗 Soul Binding & Transfer', 'Unique gear', 'Soul Binding dává gearu postupný bonus, Gear Transfer přenáší vylepšení na jiný kus.', [
  'Unique má 10 kroků vazby za 2 130 000 Kinah a 408 Soul Codex (Bound). Rebind stojí 300 000 Kinah a 3 Soul Codex: Reset (Bound).', 'Při 100 % vazbě se odemkne další Manastone slot a lze použít Soul Fuse (1 000 000 Kinah + 2 Philosopher’s Stone: Revelation).', 'Gear Transfer přenese enhancement a vazbu na Unique kus stejného slotu, vždy uspěje, stojí Transfer Stone (Unique) (Bound) ×1 nebo ×2 a žádné Kinah.'], None, 'Transfer použij před vyměněním gearu, aby se vylepšení neztratilo.', 'indigo'),
 card('🕊️ Wings', 'Mobilita + staty', 'Wings se odemykají po prvních Ascension questech (první: The One Who Perceives na Lv 5).', [
  'Wings dávají efekt, když je máš nasazená, a pasivní bonus za samotné vlastnění.', 'Létání spotřebovává Flight Power, kolekce různých wings zvyšuje jeho zásobu.', 'Flight Speed je samostatný stat; wings lze koupit i v Abyss shopu.', 'Let je klíčový i v PvP: Abyss se bojuje i ve vzduchu.'], None, 'Sbírej wings i po prvním setu, bonus za vlastnění se sčítá.', 'sky'),
 card('🐾 Pets & Genus', 'Mounts', 'Pets slouží i jako mount a rozvíjí se pomocí Soul Crystals.', [
  'Genus (rody monster): Cogni, Fera, Natura a Varian.', 'Každý genus má sadu statů proti danému rodu: Attack, Defense, Accuracy, Evasion, Critical Hit, Critical Hit Resist, Block, Block Penetration, Damage Boost a Damage Tolerance.', 'Soul Crystals jdou na Genus progresi, předplatitelé je nakoupí týdně u Wind Breeze Merchanta.', 'Stat Mount Ground Move Speed zrychluje pohyb na pet mountu.'], None, 'Genus staty vybírej podle toho, jaký rod monster nejčastěji bojuješ.', 'emerald'),
 card('🃏 Arcana', 'Karty', 'Kartový systém, který přidává staty a úrovně skillů. Je to jediný zdroj úrovní skillů nad rámec desek Daevanion.', [
  '5 slotů: Bell, Chalice, Compass, Mirror, Parchment (40 karet), grady Common až Unique.', 'Level skillu: 10 z levelingu, +5 z Daevanion a výše pouze z Arcana (max Lv 20).', 'Každá karta má jeden Deity stat jako hlavní efekt (až +20 u Unique) a až 4 řádky statů či skillů.', 'Dva sety: <strong>Primal Vigor</strong> (2 kusy: +60 PvE Attack při HP ≥ 70 %) a <strong>Magic Armor</strong> (2 kusy: obnoví 1 500 MP při MP ≤ 20 %, cooldown 30 s).', 'Levelování: Training Arcana (200 / 600 / 1 500 / 3 000 / 5 000 EXP) nebo krmení kartami stejného typu. Karty se z nepotřebných dají extrahovat na materiál.'], 'zdroj: Transcendence dungeony.', 'Stavěj kartový set podle Deity statů, které potřebuješ, ne jen podle set bonusu.', 'indigo'),
 card('🏛️ Pantheon', 'Deity staty', 'Sbírková stránka, která dává trvalé Deity staty.', [
  'Obsahuje 1 Colossus, 4 statues a 12 Pantheon art.', 'Odemyká se po prvních dvou Ascension questech.', 'Pantheon art padá z Expedition Conquest reward tables.', 'Deity staty z Pantheonu se sčítají se stejným statem z braceletů, Arcana a Monolith.'], 'trvalé Deity staty.', 'Vkládej Pantheon předměty hned po získání.', 'amber'),
 card('👗 Closet', 'Vzhled', 'Správa skinů a kostýmů nezávisle na bojových statech.', [
  'Kolekce vzhledů může dávat i drobné bonusy.', 'Vzhled odemkneš dříve, než gear zahodíš nebo rozeberešš.'], None, 'Před prodejem nebo rozebráním gearu zkontroluj, zda už máš jeho vzhled.', 'slate')])

for i, x in (('odyle', ODYLE), ('pve', PVE), ('pvp', PVP), ('other', OTHER)):
    put(i, x)

# ---------- Timers: h:m:s ----------
S = re.sub(r"function fmt\(ms\)\{.*?\n", "function fmt(ms){const s=Math.max(0,Math.floor(ms/1000)),d=Math.floor(s/86400),p=n=>String(n).padStart(2,'0');return (d?d+'d ':'')+p(Math.floor(s%86400/3600))+':'+p(Math.floor(s%3600/60))+':'+p(s%60);}\n", S, count=1)
S = S.replace('class="font-semibold text-', 'class="tabular-nums font-semibold text-')

# ---------- Arcana leftover data ----------
S = re.sub(r'const arcanaData = \{.*?\n    \};', 'const arcanaData = {};', S, count=1, flags=re.S)

# ---------- Revision pass ----------
R = [
 ('AION 2 – STRATEGICKÁ ENCYKLOPEDIE & VELITELSKÁ PŘÍRUČKA', 'AION 2 – ENCYKLOPEDIE'),
 ('AION 2 Strategická Encyklopedie a Velitelská Příručka', 'Aion 2 – Encyklopedie'),
 ('AION 2 STRATEGICKÁ ENCYKLOPEDIE & VELITELSKÁ PŘÍRUČKA &copy; 2026', 'AION 2 ENCYKLOPEDIE &copy; 2026'),
 ('Unreal Engine 5 Engine', 'Unreal Engine 5'), ('PC PURPLE / Cross-Play', 'Steam / PURPLE launcher'),
 ('Revidovaný Systém', 'Resource postavy'), ('Dvoupilířový systém: Odyle Energy (zdroj pro nárokování dungeon reward cube).', 'Odyle Energy je zdroj pro nárokování dungeon reward cube. Regenerace, cap, ceny cube a všechny způsoby, jak ji získat.'),
 ('Otevřít Odyle Průvodce', 'Otevřít Odyle systém'), ('Otevřít PvE Průvodce', 'Otevřít PvE kontent'), ('Otevřít PvP Průvodce', 'Otevřít PvP kontent'), ('Otevřít Systémy & Crafting', 'Otevřít Ostatní kontent'),
 ('9 Herních Módů', '10 aktivit'), ('6 Okruhů', '9 okruhů'), ('8 Systémů', '10 systémů'), ('Kompletní Databáze', 'Databáze statů'),
 ('Expedice (Exploration & Conquest), Daily Dungeony, Nightmare, Shugo Festival, Supply Requests, Sanctuary Raidy, Transcendence, Duty a Command Quests.', 'Expedice (Exploration a Conquest), Daily Dungeon, Nightmare, Shugo Festival, Supply Request, Sanctuary, Transcendence, Duty a Command Quests, Sealed Dungeons.'),
 ('Abyss Open World, Battlefield bojiště, Arény s Equalized Stats, Abyss Command Quests, bitvy o World Bosse a Pevnostní války.', 'Abyss Region, Abyss Points, Spacetime Rift, Battlefield, arény, Artifact Siege, Abyss Corridors, World bossové a Command Quests v Abyssu.'),
 ('Substance Morph, Crafting & Gathering, Enhancement, Transfer Crafting, Wings & Glide Canceling, Pets, Arcana karty a Šatník (Closet).', 'Substance Morph, Crafting, Gathering, Enhancement, Soul Binding, Wings, Pets, Arcana, Pantheon a Closet.'),
 ('Detailní rozpis Might, Precision, Dexterity, Intelligence, Willpower, Constitution, Božské statistiky, Hit Detection a sub-stat glosář s vyhledáváním.', 'Might, Dexterity, Intelligence, Constitution, Precision, Willpower, Deity staty a sub staty s vyhledáváním.'),
 ('Interaktivní mapa zóny World_L_A s vyhledáváním gathering nodů, skrytých kostek (Hidden Cubes), bossů a vstupů do dungeonů.', 'Interaktivní mapa zóny World_L_A s gathering nody, Hidden Cubes, bossy a vstupy do dungeonů.'),
 ('📊 Kompletní Databáze Statistik (Stats & Sub-stats)', '📊 Staty: Primary, Deity a sub staty'),
 ('Zvyšuje Attack (Sílu útoku).', 'Zvyšuje Attack.'), ('Zvyšuje Accuracy (Přesnost) a Critical Hit Rate.', 'Zvyšuje Accuracy a Critical Hit.'),
 ('Zvyšuje Status Effect Resist (Odolnost vůči efektům).', 'Zvyšuje Status Effect Resist.'), ('Zvyšuje Status Effect Chance (Šanci na aplikaci efektu).', 'Zvyšuje Status Effect Chance.'),
 ('Zvyšuje maximální hodnotu HP (Zdraví).', 'Zvyšuje HP.'), ('Crit Hit Rate & Regen Penetration', 'Critical Hit & Regeneration Penetration'),
 ('Double Chance & MP Cost Reduction', 'Double Chance & MP Cost (snižuje)'), ('Max MP & Endurance Chance', 'MP & Endurance'), ('Move Speed & Block Chance', 'Move Speed & Block'),
 ('Cooldown Red. & Endurance Penetration', 'Cooldown (snižuje) & Endurance Penetration'), ('Max HP & Regen Activation Chance', 'HP & Regeneration'),
 ('>Power Shard Damage<', '>Power Shard Damage Bonus<'), ('Zvyšuje poškození při použití Power Shardů.', 'Zvyšuje damage při použití Power Shard.'),
 ('Zvyšuje damage zezadu a ignoruje cílův Block.', 'Zvyšuje damage při útoku zezadu a ignoruje Block cíle.'), ('Zvyšuje základní Weapon Damage zbraně.', 'Posiluje Weapon Damage.'),
 ('Snižuje účinek soupeřovy zbraně.', 'Oslabuje Weapon Damage cíle.'), ('Zvyšuje šanci na dvojitý úder.', 'Zvyšuje šanci na aktivaci Double (výrazně vyšší damage).'),
 ('Šance na přidání vícečetných zásahů.', 'Zvyšuje šanci na Multi-hit (až 4 další zásahy podle Attack).'), ('Ignoruje cílův Endurance activation.', 'Ignoruje šanci cíle na aktivaci Endurance.'),
 ('Zvyšuje šanci na aktivaci Endurance.', 'Zvyšuje šanci na Endurance (sníží damage na polovinu).'),
 ('Destruction (Zikel)', 'Destruction [Zikel]'), ('Death (Triniel)', 'Death [Triniel]'), ('Wisdom (Lumiel)', 'Wisdom [Lumiel]'), ('Destiny (Marchutan)', 'Destiny [Marchutan]'),
 ('Space (Israphel)', 'Space [Israphel]'), ('Time (Siel)', 'Time [Siel]'), ('Illusion (Kaisinel)', 'Illusion [Kaisinel]'), ('Freedom (Vaizel)', 'Freedom [Vaizel]'), ('Life (Yustiel)', 'Life [Yustiel]'), ('Justice (Nezekan)', 'Justice [Nezekan]'),
 ('rozešš', 'roz'), ('rozeberešš', 'rozebereš'), ('Gradu:', 'Grady:'),
]
for a, b in R:
    S = S.replace(a, b)
S = re.sub(r'(<p class="text-amber-200/90[^>]*>)(.*?)(</p>)', r'\1Ucelený průvodce pro Aion 2 se zachováním herní terminologie. Najdeš tu Odyle systém, PvE a PvP kontent, ostatní systémy, staty, kalkulačky, limity a denní i týdenní rutinu. Hodnoty vycházejí z dat globálního klienta.\3', S, count=1, flags=re.S)
open(F, 'w', encoding='utf8').write(S)
print(len(S))
